---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  replicas: {{ pluck .Values.global.env .Values.replicas | first | default .Values.replicas._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/01-config.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
      containers:
      - name: {{ .Chart.Name | quote }}
        image: prom/cloudwatch-exporter:cloudwatch_exporter-0.9.0
        ports:
        - name: http-metrics
          containerPort: 9106
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "{{ pluck .Values.cluster .Values.aws_access_key_id | first | default .Values.aws_access_key_id._default }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{ pluck .Values.cluster .Values.aws_secret_access_key | first | default .Values.aws_secret_access_key._default }}"
        resources:
          requests:
            cpu: {{ pluck .Values.global.env .Values.resources.requests.cpu | first | default .Values.resources.requests.cpu._default }}
            memory: {{ pluck .Values.global.env .Values.resources.requests.memory | first | default .Values.resources.requests.memory._default }}
          limits:
            memory: {{ pluck .Values.global.env .Values.resources.requests.memory | first | default .Values.resources.requests.memory._default }}
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9106
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9106
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: config
          subPath: config.yml
          mountPath: /config/config.yml
      volumes:
      - name: config
        configMap:
          name: {{ printf "%s-config" .Chart.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
  ports:
  - name: http-metrics
    port: 9106
    targetPort: 9106
